config/routes.rb
SampleApp::Application.routes.draw do

  get "sessions/new"

  resources :users
  resources :videos
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/upload', :to => 'videos#new'
  
  root :to => 'pages#home'
  
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  get "pages/videos"
  

  

end

app/models/video.rb
# == Schema Information
# Schema version: 20110406175330
#
# Table name: videos
#
#  id                    :integer         not null, primary key
#  name                  :string(255)
#  description           :text
#  length                :integer
#  created_at            :datetime
#  updated_at            :datetime
#  origfile_file_name    :string(255)
#  origfile_content_type :string(255)
#  origfile_file_size    :integer
#  origfile_updated_at   :datetime
#  user_id               :integer
#  origfile_processing   :boolean
#

require 'lib/paperclip_processors/video_thumbnail'
require 'lib/paperclip_processors/video_converter'

class Video < ActiveRecord::Base
  attr_accessible :name, :description, :origfile
  attr_accessor :origfile
  belongs_to :user

  validates :name, :presence =>true
  validates :description, :presence => true
  validates :user_id, :presence => true
  validates_attachment_presence :origfile #Validation from paperclip

  has_attached_file :origfile, :styles => { :small => ['36x36#', :png],
                                            :medium => ['72x72#', :png],
                                            :large => ['640x320#', :png],
                                            :ogvvideo => { :processors => [:video_converter],
                                                            :format => 'ogv', :whiny => true },
                                            :webmvideo => { :processors => [:video_converter],
                                                            :format => 'webm', :whiny => true },
                                            :x264video => { :processors => [:video_converter],
                                                            :format => 'mp4', :whiny => true }
                                           },
                                :processors => [:video_thumbnail ]

  process_in_background :origfile
  default_scope :order => 'videos.updated_at DESC'
  before_destroy :remove_attachments

  def still_processing?
    self.origfile_processing
  end

  protected
    def remove_attachments
      destroy_attached_files
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate, :only => [:new, :create, :destroy, :edit, :update]

  def index
    @videos = Video.paginate(:page => params[:page])
  end

  def create
    @video = current_user.videos.new(params[:video])
    @video.length = 400
    if @video.save
      redirect_to videos_url
    else
      render :new 
    end
  end

  def new
    @video = Video.new
  end

  def show
    @video =Video.find(params[:id])
    @embed = render_to_string 'embedVideo', :layout => false
    @embed.gsub!("/system", "system") #Get rid of double slashes in link
    @embed = CGI.escapeHTML(@embed)
  end

  def delete
  end

  def destroy
    Video.find(params[:id]).destroy
    redirect_to videos_url
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    if @video.update_attributes(params[:video])
      flash[:success] = "Video Updated"
      redirect_to @video
    else
      render :edit
    end
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_embedVideo.html.erb
  <script src="<%= root_url%>javascripts/video-js/video.js" type="text/javascript" charset="utf-8"></script>
  <link rel="stylesheet" href="<%= root_url%>stylesheets/video-js.css" type="text/css" media="screen" title="Video JS" charset="utf-8"></link>

  <script type="text/javascript" charset="utf-8">
      VideoJS.setupAllWhenReady();
  </script>

    <div class="video-js-box">
      <video class="video-js" width="640" height="264" controls preload poster=<%= root_url + video.origfile.url(:large) %> >

        <source src= <%= root_url + video.origfile.url(:x264video) %> type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"' />
        <source src= <%= root_url + video.origfile.url(:webmvideo) %> type='video/webm; codecs="vp8, vorbis"' />
        <source src= <%= root_url + video.origfile.url(:ogvvideo)  %> type='video/ogg; codecs="theora, vorbis"' />

        <object class="vjs-flash-fallback" width="640" height="264" type="application/x-shockwave-flash"
          data="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf">
          <param name="movie" value="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf" />
          <param name="allowfullscreen" value="true" />
          <param name="flashvars" value='config={"playlist":["<%= root_url + video.origfile.url(:large) %>", {"url": "<%= root_url + video.origfile.url(:x264video) %>","autoPlay":false,"autoBuffering":true}]}' />
          <img src= "<%= root_url + video.origfile.url(:large) %>" width="640" height="264" alt="Poster Image"
            title="No video playback capabilities." />
        </object>
      </video>
    </div>

app/views/videos/_showVideo.html.erb
<% if not video.still_processing? %>
<%= javascript_include_tag "video-js/video" %>
<%= stylesheet_link_tag "video-js" %>

  <script type="text/javascript" charset="utf-8">
      // Add VideoJS to all video tags on the page when the DOM is ready
      VideoJS.setupAllWhenReady();
      
  </script>

  <!-- Begin VideoJS -->
    <div class="video-js-box">
      <!-- Using the Video for Everybody Embed Code http://camendesign.com/code/video_for_everybody -->
      <video class="video-js" width="640" height="264" controls preload poster=<%= video.origfile.url(:large) %> >

        <source src= <%= video.origfile.url(:x264video) %> type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"' />
        <source src= <%= video.origfile.url(:webmvideo) %> type='video/webm; codecs="vp8, vorbis"' />
        <source src= <%= video.origfile.url(:ogvvideo)  %> type='video/ogg; codecs="theora, vorbis"' />

        <!-- Flash Fallback. Use any flash video player here. Make sure to keep the vjs-flash-fallback class. -->
        <object class="vjs-flash-fallback" width="640" height="264" type="application/x-shockwave-flash"
          data="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf">
          <param name="movie" value="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf" />
          <param name="allowfullscreen" value="true" />
          <param name="flashvars" value='config={"playlist":["<%= video.origfile.url(:large) %>", {"url": "<%= video.origfile.url(:x264video) %>","autoPlay":false,"autoBuffering":true}]}' />
          <!-- Image Fallback. Typically the same as the poster image. -->
          <img src= "<%= video.origfile.url(:large) %>" width="640" height="264" alt="Poster Image"
            title="No video playback capabilities." />
        </object>
      </video>

    </div>
    <!-- End VideoJS -->
<% else %>
  <p>Video is still converting</p>
<% end %>

app/views/videos/create.html.erb
-<h1>Videos#create</h1>
<p>Find me in app/views/videos/create.html.erb</p>

app/views/videos/delete.html.erb
<h1>Videos#delete</h1>
<p>Find me in app/views/videos/delete.html.erb</p>

app/views/videos/edit.html.erb
<h1>Videos#update</h1>
<p>Find me in app/views/videos/edit.html.erb</p>
<%= form_for @video, :html => { :multipart => true }  do |form| %>
      <div class="field">
        <%= form.label 'Name:' %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label 'Beschreibung:' %>
        <%= form.text_field :description %>
      </div>

      <div class="actions">
        <%= form.submit "Save" %>
      </div>
<% end %>

app/views/videos/embedVideo.html.erb
<%= render 'embedVideo', :video => @video %>

app/views/videos/index.html.erb
<h1>Videos</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Beschreibung</th>
    <th>Besitzer</th>
  </tr>
<%= will_paginate %>
<% @videos.each do |video| %>
  <% @user = User.find_by_id(video.user_id) %>
  <tr>
    <td><%= link_to video.name, video %></td>
    <td><%= video.description[0, 10] + "..." %></td>
    <td><%= link_to @user.name, @user%></td>
  </tr>
<% end %>
</table>
<%= will_paginate %>

app/views/videos/new.html.erb
<h1>Upload</h1>

<%= form_for @video, :html => { :multipart => true }  do |form| %>
  <%= render 'shared/error_messages', :object =>@video %>
    <div class="field">
      <%= form.label 'VideoDatei:' %>
      <%= form.file_field :origfile %>
    </div>

    <div class="field">
      <%= form.label 'Name:' %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label 'Beschreibung:' %>
      <%= form.text_field :description %>
    </div>

    <div class="actions">
      <%= form.submit "Upload" %>
    </div>

<% end %>

app/views/videos/show.html.erb
<h1><%= @video.name %></h1>
<% if current_user %>
  <%= link_to 'Destroy', @video, :confirm => 'Are you sure?', :method => :delete unless not current_user.admin? %>
  <%= link_to 'Edit', edit_video_path(@video) unless not current_user.admin? %>
<% end %>
<%= render 'showVideo', :video => @video %>
<p class = "round" ><%= @video.description %></p>
<% if not @video.still_processing? %>
  <p><a href="#content" title="Content Lightbox">EmbedCode</a> </p>

  <div class="lightbox" id="content">
    <div class="w60p h400 scroll">
      <p><%= @embed %></p>
    </div>
    <p class="close"><a href="#" title="Close This Content Lightbox">Close <span>X</span></a></p>
  </div>
<% end %>

app/views/videos/upload.html.erb
<h1>Upload</h1>
<p>Find me in app/views/videos/new.html.erb</p>


<%= form_for @video, :html => { :multipart => true }  do |form| %>
  <%= render 'shared/error_messages', :object =>@video %>
    <div class="field">
      <%= form.label 'VideoDatei:' %>
      <%= form.file_field :origfile %>
    </div>

    <div class="field">
      <%= form.label 'Name:' %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label 'Beschreibung:' %>
      <%= form.text_field :description %>
    </div>

    <div class="actions">
      <%= form.submit "Upload" %>
    </div>


<% end %>