config/routes.rb
SampleApp::Application.routes.draw do

  get "sessions/new"

  resources :users
  resources :videos
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/upload', :to => 'videos#new'
  
  root :to => 'pages#home'
  
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  get "pages/videos"
  

  

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Help", help_path %> </li>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to image_tag("stream.png", :alt => "VideoBin", :class => "round"), root_path %>
  <nav class="round">
    <ul>
        <li><%= link_to "Upload", upload_path %></li>
        <li><%= link_to "Videos", videos_path  %></li>
      <% if not signed_in? %>
        <li><%= link_to "Sign In", signin_path %></li>
        <li><%= link_to "Sign Up", signup_path %></li>
      <% elsif signed_in? %>
        <li><%= link_to "UserList", users_path%></li>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag :defaults %> <!-- For example -->
    <%= render 'layouts/stylesheets' %>
    </head>

  <body>
    <div class="container">
       <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
          
      </section>
      <%#*<section class="round"><%= yield %></section>%>
      <%#*<br />%>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>



  


</html>